### ISSUE TITLE
Console errors with <StylesPlaceholder />

### ISSUE THREAD

**Issue by lmjcbs** [mantinedev/remix-template#2]
Migrated over to 5.0.0 but I am now faced with console errors, I believe it's due to the <style> tags on the server and the client being out of sync with the use of the placeholder component.

Using a fresh install of this template with `<StylesPlaceholder />` in `root.tsx`, I receive the following console error in the browser:
`Warning: Did not expect server HTML to contain a <style> in <head>.`
<img width="619" alt="Screenshot 2022-07-27 at 20 38 05" src="https://user-images.githubusercontent.com/93728581/181357570-f1762b03-0630-46d5-bc55-8a463c63262a.png">

Removing `<StylesPlaceholder />` from `root.tsx` removes the console error, but unsurprisingly now causes the styles to flash upon initial load.

Any tips on how to fix these console errors with use of the `<StylesPlaceholder />` component?

**Comment by rtivital** [comment]
Nope, if it is a huge issue for you, you can setup your own server-side rendering with `@mantine/ssr` package following remix documentation – https://remix.run/docs/en/v1/guides/styling#css-in-js-libraries

**Comment by zwying0814** [comment]
> 

Did you solve this problem please? I have the same situation as you, hope you can provide a minimal example, thanks
